build:
  image: node:10-alpine
  stage: deploy
  script:
    - npm ci
    - npm run build
    - mv dist public # rename the dist folder (result of npm run build)
    - gzip -k -6 $(find public -type f) # compress the artifacts
  artifacts:
    paths:
      - public # so you can look at the generated site via the gitlab artifacts site


# doing the same thing again when pushing to master because only the
# master version should be available via gitlab pages
pages: # the job to publish the site
  image: node:10-alpine
  stage: deploy
  script:
    - npm ci
    - npm run build
    - mv dist public # rename the dist folder (result of npm run build)
    - gzip -k -6 $(find public -type f) # compress the artifacts
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - master
