stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: eu-central-1
  BUCKET_NAME: serverless-game-gitlab-build

buildNpm:
  image: node:10-alpine
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

deployS3:
  image: python:3.7-alpine3.9
  stage: deploy
  dependencies:
    - buildNpm
  before_script:
    - pip install awscli
  script:
    - aws s3 cp dist s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/${CI_COMMIT_REF_SLUG}
